sudo: false
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

matrix:
    include:
    - os: linux
      jdk:  oraclejdk8
      install: true
    - os: linux
      jdk:  oraclejdk9
      install: true
    - os: osx
      install: true

language: java



#jdk:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then oraclejdk8; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then oraclejdk9; fi

before_script:
  - sh ./gradlew --version
  
script:
    - sh ./gradlew clean test
    
#after_success:
#  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
