sudo: false
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

os:
  - linux
  - osx

language: java

#install: true

jdk:
  - oraclejdk8
  - oraclejdk9

before_script:
  - bash ./gradlew --version
  
script:
    - bash ./gradlew clean test
    
#after_success:
#  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
