sudo: false

matrix:
    include:
    - os: linux
      language: java
      jdk:  oraclejdk8
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk9
      install: true
    - os: osx
      language: java
      osx_image: xcode9.2
      install: true
    - os: osx
      language: java
      osx_image: xcode9.2
      install: brew tap caskroom/cask && brew cask info java && brew cask reinstall java

before_script:
  - sh ./gradlew --version
  
script:
    - sh ./gradlew clean test
    
#after_success:
#  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
