sudo: false
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

os:
  - linux
  - osx
  - os: osx
      osx_image: xcode9.2

language: java

install: true

#jdk:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then oraclejdk8; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then oraclejdk9; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use oraclejdk9 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask && brew install java; fi
  - sh ./gradlew --version
  
script:
    - sh ./gradlew clean test
    
#after_success:
#  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
